import { useEffect, useState } from 'react';
import axios from 'axios';
import { useParams, useNavigate } from 'react-router-dom';

const Agreement = () => {
  const { id } = useParams();
  const [event, setEvent] = useState(null);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    const fetchEvent = async () => {
      try {
        // Hum events list mangwa kar filter kar rahe hain (Simple approach)
        // Production mein direct single event API honi chahiye, par ye chalega
        const res = await axios.get('/api/events');
        const foundEvent = res.data.find(e => e._id === id);
        
        if (foundEvent) {
          setEvent(foundEvent);
        } else {
          alert("Event not found!");
          navigate('/');
        }
      } catch (error) {
        console.error(error);
      } finally {
        setLoading(false);
      }
    };
    fetchEvent();
  }, [id, navigate]);

  if (loading) return <div style={{textAlign:'center', padding:'50px'}}>Generating Legal Doc... ⚖️</div>;
  if (!event) return null;

  return (
    <div style={{ padding: '40px 20px', fontFamily: 'Times New Roman, serif', maxWidth: '800px', margin: '0 auto', background: '#fff', boxShadow: '0 0 20px rgba(0,0,0,0.1)', minHeight: '100vh' }}>
      
      {/* HEADER */}
      <div style={{ textAlign: 'center', borderBottom: '2px solid #000', paddingBottom: '20px', marginBottom: '30px' }}>
        <h1 style={{ textTransform: 'uppercase', letterSpacing: '2px', fontSize: '2rem' }}>Sponsorship Agreement</h1>
        <p style={{ fontStyle: 'italic', color: '#555' }}>Official Memorandum of Understanding</p>
      </div>

      {/* BODY */}
      <div style={{ lineHeight: '1.8', fontSize: '1.1rem' }}>
        <p>
          This Agreement is made on <strong>{new Date().toLocaleDateString()}</strong>, by and between:
        </p>

        <div style={{ background: '#f8fafc', padding: '15px', border: '1px solid #ddd', margin: '15px 0' }}>
          <strong>THE SPONSOR:</strong> {event.sponsorName} ({event.sponsorEmail})<br/>
          <strong>THE ORGANIZER:</strong> Campus Event Student Committee
        </div>

        <p>
          WHEREAS, the Organizer is hosting an event titled <strong>"{event.title}"</strong> on <strong>{new Date(event.date).toLocaleDateString()}</strong> at <strong>{event.location}</strong>.
        </p>

        <p>
          WHEREAS, the Sponsor desires to sponsor the Event by providing financial support in the amount of:
        </p>

        <h2 style={{ textAlign: 'center', margin: '30px 0', fontSize: '2.5rem', color: '#166534' }}>
          ₹ {event.budget}
        </h2>

        <p>
          NOW, THEREFORE, the parties agree as follows:
          <ol>
            <li>The Sponsor agrees to pay the full amount within 2 business days.</li>
            <li>The Organizer agrees to display the Sponsor's logo on all marketing materials.</li>
            <li>This agreement is binding and enforceable by law.</li>
          </ol>
        </p>
      </div>

      {/* SIGNATURES */}
      <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '60px', paddingTop: '20px', borderTop: '1px dashed #000' }}>
        <div style={{ textAlign: 'center' }}>
          <p style={{ fontFamily: 'cursive', fontSize: '1.5rem', color: '#2563eb' }}>{event.sponsorName}</p>
          <p style={{ borderTop: '1px solid #000', width: '200px', margin: '0 auto' }}>Signature of Sponsor</p>
        </div>
        <div style={{ textAlign: 'center' }}>
            <p style={{ fontFamily: 'cursive', fontSize: '1.5rem', color: '#2563eb' }}>CampusSponsor System</p>
            <p style={{ borderTop: '1px solid #000', width: '200px', margin: '0 auto' }}>Digitally Verified</p>
        </div>
      </div>

      {/* FOOTER ACTIONS */}
      <div style={{ marginTop: '50px', textAlign: 'center', display: 'flex', gap: '20px', justifyContent: 'center' }}>
        <button onClick={() => window.print()} style={{ padding: '12px 25px', background: '#334155', color: 'white', border: 'none', cursor: 'pointer', borderRadius: '5px', fontWeight: 'bold' }}>
          🖨️ Print Agreement
        </button>
        <button onClick={() => navigate('/')} style={{ padding: '12px 25px', background: 'transparent', border: '2px solid #334155', cursor: 'pointer', borderRadius: '5px', fontWeight: 'bold' }}>
          Go to Home
        </button>
      </div>

      <p style={{textAlign:'center', marginTop:'40px', fontSize:'0.8rem', color:'#aaa'}}>Generated by CampusSponsor ID: {event._id}</p>
    </div>
  );
};

export default Agreement;