import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import toast from 'react-hot-toast';
import { jsPDF } from "jspdf";

const EventDetails = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [event, setEvent] = useState(null);
  const [amount, setAmount] = useState('');
  const [comment, setComment] = useState('');
  const [loading, setLoading] = useState(false);
  
  const user = JSON.parse(localStorage.getItem('user'));

  const fetchEvent = async () => {
    try {
      const { data } = await axios.get(`/api/events/${id}`);
      setEvent(data);
    } catch (error) { toast.error("Event not found"); }
  };

  useEffect(() => { fetchEvent(); }, [id]);

  const mySponsorship = event?.sponsors?.find(s => s.sponsorId === user?._id && s.status === 'verified');
  const isFullyFunded = event?.raisedAmount >= event?.budget;

  // 👇 PROFESSIONAL PDF GENERATOR
  const downloadAgreement = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // 1. HEADER
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(44, 62, 80); // Dark Blue
    doc.text("SPONSORSHIP AGREEMENT", pageWidth / 2, 20, { align: "center" });
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Ref ID: CSP-${mySponsorship.paymentId ? mySponsorship.paymentId.slice(-8).toUpperCase() : 'GEN'}`, 160, 10);

    // Line Divider
    doc.setLineWidth(0.5);
    doc.setDrawColor(200);
    doc.line(20, 25, 190, 25);

    // 2. PARTIES INVOLVED
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.setFont("helvetica", "normal");
    doc.text(`This Agreement is entered into on ${new Date().toLocaleDateString()} by and between:`, 20, 40);

    // Sponsor Info
    doc.setFont("helvetica", "bold");
    doc.text("THE SPONSOR:", 20, 50);
    doc.setFont("helvetica", "normal");
    const sponsorName = mySponsorship.companyName || user.companyName || user.name;
    doc.text(`${sponsorName}`, 60, 50);
    doc.text(`(${user.email})`, 60, 55);

    // Organizer Info
    doc.setFont("helvetica", "bold");
    doc.text("THE ORGANIZER:", 20, 65);
    doc.setFont("helvetica", "normal");
    const organizerName = event.user?.name || "College Representative";
    doc.text(`${organizerName}`, 60, 65);
    doc.text(`(Event Lead)`, 60, 70);

    // 3. EVENT DETAILS (Grey Box)
    doc.setFillColor(245, 247, 250); // Light Grey Background
    doc.rect(20, 80, 170, 35, "F"); 
    
    doc.setFont("helvetica", "bold");
    doc.text("EVENT DETAILS", 25, 90);
    doc.setFont("helvetica", "normal");
    doc.text(`Event Name: ${event.title}`, 25, 100);
    doc.text(`Date: ${new Date(event.date).toLocaleDateString()}`, 100, 100);
    doc.text(`Location: ${event.location}`, 25, 110);

    // 4. FINANCIALS
    doc.setFont("helvetica", "bold");
    doc.text("CONTRIBUTION DETAILS", 20, 130);
    doc.setFont("helvetica", "normal");
    doc.text(`The Sponsor agrees to provide financial support of:`, 20, 140);
    
    doc.setFontSize(16);
    doc.setTextColor(39, 174, 96); // Green Color for Money
    doc.text(`INR ${mySponsorship.amount}/-`, 20, 150);
    
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(`Transaction Status: PAID & VERIFIED (ID: ${mySponsorship.paymentId})`, 20, 160);

    // 5. TERMS & CONDITIONS
    doc.setFont("helvetica", "bold");
    doc.text("TERMS AND CONDITIONS", 20, 180);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const terms = [
        "1. The Organizer agrees to use the funds strictly for the event mentioned above.",
        "2. The Organizer will provide branding/marketing exposure to the Sponsor as discussed.",
        "3. This agreement serves as an official proof of payment and partnership.",
        "4. Any refunds are subject to the platform's refund policy (7 days prior notice).",
        "5. This document is electronically generated and is valid without a physical seal."
    ];
    let yPos = 190;
    terms.forEach(term => {
        doc.text(term, 20, yPos);
        yPos += 7;
    });

    // 6. SIGNATURES
    doc.setLineWidth(0.5);
    doc.line(20, 250, 80, 250); // Line 1
    doc.line(130, 250, 190, 250); // Line 2
    
    doc.setFont("helvetica", "bold");
    doc.text("Authorized Signature", 20, 255);
    doc.text("Authorized Signature", 130, 255);
    
    doc.setFont("helvetica", "normal");
    doc.text("(Sponsor)", 20, 260);
    doc.text("(Organizer)", 130, 260);

    // 7. FOOTER
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by CampusSponsor | Connecting Colleges & Corporates", pageWidth / 2, 280, { align: "center" });

    doc.save(`${event.title}_Official_Agreement.pdf`);
    toast.success("Professional Agreement Downloaded!");
  };

  const handlePayment = async (e) => {
    e.preventDefault();
    if (!user) return navigate('/login');
    if (user.role !== 'sponsor') return toast.error("Only Sponsors can pay!");
    
    try {
        const config = { headers: { Authorization: `Bearer ${user.token}` } };
        const meRes = await axios.get('/api/users/me', config);
        if (!meRes.data.isVerified) return toast.error("🚫 Not Verified by Admin!");
    } catch (err) { return; }

    if (!amount || amount < 1) return toast.error("Enter valid amount");

    setLoading(true);
    try {
        const { data: order } = await axios.post('/api/payment/order', { amount, eventId: id });

        const options = {
            key: "rzp_test_RzpjqjoYNvSTMY",
            amount: order.amount,
            currency: "INR",
            name: "CampusSponsor",
            description: `Sponsoring ${event.title}`,
            order_id: order.id,
            handler: async function (response) {
                try {
                    const verifyData = {
                        razorpay_order_id: response.razorpay_order_id,
                        razorpay_payment_id: response.razorpay_payment_id,
                        razorpay_signature: response.razorpay_signature,
                        eventId: id,
                        amount: amount,
                        userId: user._id,
                        userName: user.name,
                        userEmail: user.email,
                        companyName: user.companyName,
                        comment: comment
                    };
                    await axios.post('/api/payment/verify', verifyData);
                    toast.success("🎉 Payment Successful!");
                    fetchEvent(); 
                } catch (error) { toast.error("Verification Failed"); }
            },
            prefill: { name: user.name, email: user.email, contact: user.phone },
            theme: { color: "#2563eb" }
        };
        const rzp1 = new window.Razorpay(options);
        rzp1.open();
    } catch (error) {
        console.error(error);
        toast.error(error.response?.data?.message || "Payment Failed");
    } finally { setLoading(false); }
  };

  if (!event) return <div style={{textAlign:'center', marginTop:'50px'}}>Loading...</div>;

  const percent = Math.min((event.raisedAmount / event.budget) * 100, 100);

  return (
    <div style={{ maxWidth: '800px', margin: '40px auto', padding: '20px', fontFamily:'Poppins' }}>
      
      {/* HEADER */}
      <div style={{ background: 'white', padding: '30px', borderRadius: '15px', boxShadow: '0 4px 20px rgba(0,0,0,0.1)' }}>
        <h1 style={{ fontSize: '2.5rem', color: '#1e293b', marginBottom: '10px' }}>{event.title}</h1>
        
        <div style={{background:'#e2e8f0', borderRadius:'10px', height:'20px', width:'100%', marginBottom:'10px', overflow:'hidden'}}>
            <div style={{width: `${percent}%`, background: isFullyFunded ? '#22c55e' : '#3b82f6', height:'100%', transition:'0.5s'}}></div>
        </div>
        <div style={{display:'flex', justifyContent:'space-between', fontSize:'0.9rem', color:'#64748b', marginBottom:'20px'}}>
            <span>Raised: ₹{event.raisedAmount || 0}</span>
            <span>Goal: ₹{event.budget}</span>
        </div>

        <p style={{ fontSize: '1.1rem', lineHeight: '1.6', color: '#334155', marginBottom: '30px' }}>{event.description}</p>
      </div>

      {/* ACTION SECTION */}
      <div style={{ marginTop: '30px', background: '#f8fafc', padding: '30px', borderRadius: '15px', border: '2px dashed #cbd5e1' }}>
        
        {mySponsorship ? (
            <div style={{textAlign:'center'}}>
                <h2 style={{color:'#16a34a'}}>✅ You are a Sponsor!</h2>
                <p style={{color:'#64748b', marginBottom:'20px'}}>Thank you for contributing ₹{mySponsorship.amount}.</p>
                <button onClick={downloadAgreement} style={{padding:'15px 30px', background:'#1e293b', color:'white', border:'none', borderRadius:'8px', cursor:'pointer', fontWeight:'bold', fontSize:'1rem', boxShadow:'0 4px 10px rgba(0,0,0,0.2)'}}>
                    📄 Download Professional Agreement
                </button>
            </div>
        ) : isFullyFunded ? (
            <div style={{textAlign:'center'}}>
                <h2 style={{color:'#22c55e'}}>🎉 Event Fully Funded!</h2>
                <p>No more sponsors needed for this event.</p>
            </div>
        ) : user?.role === 'sponsor' ? (
            <>
                <h2 style={{ textAlign: 'center', color: '#1e293b' }}>💳 Make Payment</h2>
                <p style={{ textAlign: 'center', color: '#64748b', fontSize: '0.9rem', marginBottom: '20px' }}>Remaining Need: ₹{event.budget - (event.raisedAmount || 0)}</p>
                <form onSubmit={handlePayment} style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                    <input type="number" placeholder="Enter Amount (₹)" value={amount} onChange={e=>setAmount(e.target.value)} required style={{ padding: '12px', borderRadius: '8px', border: '1px solid #ccc' }} />
                    <textarea placeholder="Message (Optional)" value={comment} onChange={e=>setComment(e.target.value)} style={{ padding: '12px', borderRadius: '8px', border: '1px solid #ccc', height: '80px' }} />
                    <button type="submit" disabled={loading} style={{ padding: '15px', background: user.isVerified ? '#2563eb' : '#94a3b8', color: 'white', border: 'none', borderRadius: '8px', fontSize: '1.1rem', fontWeight: 'bold', cursor: user.isVerified ? 'pointer' : 'not-allowed' }}>
                        {loading ? 'Processing...' : (user.isVerified ? 'Pay Now & Generate Agreement' : 'Verification Pending 🔒')}
                    </button>
                </form>
            </>
        ) : (
            <div style={{ textAlign: 'center', color: '#64748b' }}>Login as Sponsor to Pay.</div>
        )}
      </div>
    </div>
  );
};

export default EventDetails;